### ISSUE TITLE
FC047: False positive on attribute used as an index

### ISSUE THREAD

**Issue by MarkGibbons** [acrmp/foodcritic#483] opened 2016-09-12 21:33 UTC
node.default['nix_server']['directories']["/u/#{node['sf_rewards_enroll']['env']}"] = { }

gets FC047: Attribute assignment does not specify precedence: ./recipes/attributes.rb:13. 

This code doesn't generate an alert

a = node['sf_rewards_enroll']['env']
node.default['nix_server']['directories']["/u/#{a}"] = { }

**Comment by grimm26** [comment] 2016-11-21 20:55
Looks like dupe of #225

**Comment by tas50** [comment] 2017-04-08 20:23
Closing as a duplicate of #225

**Closed by tas50** 2017-04-08 20:23 UTC
