### ISSUE TITLE
files_to_process doesn't include child paths under templates/default/ 

### ISSUE THREAD

**Issue by ruizink** [acrmp/foodcritic#265] opened 2014-09-21 21:05 UTC
This piece of code doesn't scan *.erb files, other than the ones that seat under templates/default/ directory:

```ruby
template do |ast, filename|
  puts filename
end
```

I'll do a pull request with the fix right away.

Cheers.

**Comment by odcinek** [comment] 2015-03-21 07:23
I was unable to reproduce on master, and the source looks right. Closing.

**Closed by odcinek** 2015-03-21 07:23 UTC

**Comment by odcinek** [comment] 2015-03-21 07:29
Er, this needs correction - recursively scanning under `templates/default/` would be wrong, as according to resource docs `source` is *relative*.
